# Generated by Django 3.2.16 on 2022-10-18 21:25

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=15)),
                ('model', models.CharField(max_length=15)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('overview', models.TextField()),
                ('specifications', models.TextField()),
                ('plans', models.TextField()),
                ('build_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('featured_excerpt', models.CharField(blank=True, max_length=300)),
                ('likes', models.ManyToManyField(blank=True, related_name='build_likes', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_builds', to=settings.AUTH_USER_MODEL)),
                ('saves', models.ManyToManyField(blank=True, related_name='build_saves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('body', models.TextField()),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_comments', to='webapp.build')),
            ],
            options={
                'ordering': ['comment_date'],
            },
        ),
    ]
